### PR TITLE
add working config for 4.9.9

### PR DESCRIPTION
**Pull request by maltoe**
Hey Guillaume,

this repository is the first hit on google when you search for "thinkpad x260 kernel config", yet there is no kernel config here! Feel free to take your own, just thought there should at least be something here.

Includes luks specific options, but no btrfs or docker related options.

cheers,
malte

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
@maltoe ahah I have forget this repos !

But this is my own setup, so there is a few added options, and I am actually on 4.9.7
* qemu, systemd, docker, luks, btrfs

I suggest you take mine, then try to iterate on it to disable what you don't need (btrfs, docker).

**Comment by GuillaumeSeren** [comment]
I fixed it on #3 @maltoe

**Comment by GuillaumeSeren** [comment]
Closing

**Comment by maltoe** [comment]
@GuillaumeSeren :+1:

**Pull request closed without merging**
